routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('/product', App\Http\Controllers\ProductController::class)->middleware('auth');
Route::get('/categories', [App\Http\Controllers\ProductController::class, 'categories'])->middleware('auth');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    protected $guarded = [];
}

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function user(){
       return $this->belongsTo(User::class, 'user_id');
    }

    public function category(){
        return $this->belongsToMany(Category::class, 'product_categories');
    }
}

app/Models/ProductCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ProductCategory extends Model
{
    use HasFactory;
    protected $guarded = [];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function products(){
        return hasMany(Product::class, 'user_id', 'id');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Services\ProductService;
use DataTables;
use App\Http\Requests\ProductRequest;

class ProductController extends Controller
{
    protected $service;

    public function __construct(ProductService $service){
        $this->service = $service;
    }

    public function index(){
        $products = $this->service->index();
        return Datatables::of($products)
                ->addIndexColumn()
                ->addColumn('action', function($row){
                    $actionBtn = '<a href="javascript:void(0)" class="edit btn btn-success btn-sm">Edit</a> <a href="javascript:void(0)" data-rowid="'.$row->id.'" class="delete btn btn-danger btn-sm">Delete</a>';
                    return $actionBtn;
                })
                ->addColumn('category', function($categoies){
                    $category_text = '';
                    foreach($categoies->category as $category)
                    {
                        $category_text .= $category->type.' - ';
                    }
                    return $category_text;
                })
                ->rawColumns(['action', 'category'])
                ->make(true);
    }

    public function categories(){
        return $this->service->categories();
    }

    public function store(ProductRequest $request){
        return $this->service->store($request->validated());
    }

    public function update(ProductRequest $request, $id){
        return $this->service->edit($request->validated(), $id);
    }

    public function destroy($id){
        $this->service->destroy($id);
        return ['success' => true, "message" => "deleted"];
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <button type="button" class="btn btn-success product_add">Add Product</button>
                    <div class="container mt-5">
                        <h2 class="mb-4">Products</h2>
                        <table class="table table-bordered yajra-datatable">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>name</th>
                                    <th>quantity</th>
                                    <th>price</th>
                                    <th>category</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>

                        <div class="modal"  role="dialog" style="z-index: 1051 !important;">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Product</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                <form class="product_form">
                                    <input type="hidden" name="id">
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Product Name</label>
                                        <input type="text" name="name" class="form-control" id="product_name" aria-describedby="emailHelp" placeholder="Enter email">
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Product Price</label>
                                        <input type="number" name="price" class="form-control" id="product_price" aria-describedby="emailHelp" placeholder="Enter email">
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Product Quantity</label>
                                        <input type="number" name="quantity" class="form-control" id="product_price" aria-describedby="emailHelp" placeholder="Enter email">
                                    </div>
                                    <div class="form-group select_box">
                                        <label for="Category">Category</label>
                                        <select name="categories[]" id="mySelect2" class="form-control" multiple="multiple" >
                                        </select>
                                    </div>
                                </form>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-primary save">Save changes</button>
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
$(document).ready(function(){
    /**
     * get all products and paginate it
     */
    var table = $('.yajra-datatable').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('product.index') }}",
        columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex'},
            {data: 'name', name: 'name'},
            {data: 'quantity', name: 'quantity'},
            {data: 'price', name: 'price'},
            {data: 'category', name: 'category'},
            {
                data: 'action',
                name: 'action',
                orderable: true,
                searchable: true
            },
        ]
    });

    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });

     /**
     * setup select2 library
     */
    $('#mySelect2').select2({
        selectOnClose: true,
        placeholder: "Categories",
    });

    /**
     * get all categories
     */
    function Categories(){
        $.ajax({
            url: "/categories",
            type: 'get',
            dataType: "JSON",
            success: function(data){
                $.each(data, function (i, item) {
                $('#mySelect2').append($('<option>', {
                    value: item.id,
                    text : item.type
                }));
            });
            }
        });
    }

    /**
     * open modal and insert product to create then save
     */
    $(document).on('click', '.product_add', function(){
        $('.modal').find('.modal-title').text('Create Product');
        $('.select_box').css('display', 'block');
        $('.modal').modal('show');
        Categories();
        $('.save').click(function(){
            $validate_status = 0;
            var data = $('.product_form').serializeArray();
            $.each(data, function (index,value) {
                if(value.name != 'id' && value.value == '' || value.value == null){
                    alert("all fields required");
                    $validate_status = 1;
                    return false;
                }
            });

            if($validate_status == 1){
                $validate_status == 0;
                return;
            }
            console.log(data);
            $.ajax({
            url: "/product",
            type: 'POST',
            data: data,
            dataType: "JSON",
            success: function(data){
                table.draw();
                $('.modal').modal('hide');
            }
        });
        });

    });

    /**
     * open modal and edit product to update then save
     */
    $(document).on('click', '.edit', function(){
        $('.modal').find('.modal-title').text('Update Product');
        $('.select_box').css('display', 'none');
        $('.modal').modal('show');
        var rowData = table.row($(this).parents('tr')).data();
        $('.product_form').find('input[name="id"]').val(rowData.id);
        $('.product_form').find('input[name="name"]').val(rowData.name);
        $('.product_form').find('input[name="price"]').val(rowData.price);
        $('.product_form').find('input[name="quantity"]').val(rowData.quantity);
        $('.save').click(function(){
            $validate_status = 0;
            var data = $('.product_form').serializeArray();
            $.each(data, function (index,value) {
                if(value.value == '' || value.value == null){
                    alert("all fields required");
                    $validate_status = 1;
                    return false;
                }
            });
            if($validate_status == 1){
                $validate_status == 0;
                return;
            }
            console.log(data);
            $.ajax({
            url: "/product/"+rowData.id,
            type: 'PUT',
            data: data,
            dataType: "JSON",
            success: function(data){
                table.draw();
                $('.product_form').find('input[name="id"]').val('');
                $('.product_form').find('input[name="name"]').val('');
                $('.product_form').find('input[name="price"]').val('');
                $('.product_form').find('input[name="quantity"]').val('');
                $('.modal').modal('hide');
            }
         });
        });

    });

    /**
     * get product to delete then if choose yes then delete product
     */
    $(document).on('click', '.delete', function(){
        if(!confirm("Are you sure?")) return;
        var id = $(this).data('rowid');
        var el = $(this);
        console.log(id);
        $.ajax({
            url: "/product/"+id,
            type: 'DELETE',
            dataType: "JSON",
            success: function(data){
            if(data.success){
                table.row(el.parents('tr')).remove().draw();
            }
            }
        });
    });

});

</script>

@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"/>
    <link href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

<!-- Scripts -->

    @vite(['resources/sass/app.scss', 'resources/js/app.js'])
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>


</body>
</html>